/*
 * hello_cgi.c - Monios CGI test program.
 *
 * Built as a normal PE .exe and placed under the httpd docroot
 * (C:\Monios\www\hello_cgi.exe). When httpd receives a request for a
 * .exe it runs this program via SYS_EXEC_CAPTURE and returns stdout as
 * the HTTP response body.
 */

#include "stdio.h"
#include "appsys.h"

int main(int argc, char **argv)
{
    (void) argc;
    (void) argv;

    fputs("<html><body>");
    fputs("<h1>Hello from CGI!</h1>");
    fputs("<p>This page was generated by a Monios .exe CGI program.</p>");
    fputs("</body></html>");
    return 0;
}
