#!/usr/bin/env python3
"""Generate test_vectors.h for the Monios DEFLATE inflate host test.

Each vector: a raw DEFLATE bitstream (zlib stream with the 2-byte CMF/FLG
header and the 4-byte Adler-32 trailer stripped) plus the expected expanded
bytes.  Level 9 forces the widest possible use of length/distance codes,
including the 277..285 length-symbol range that historically broke this
implementation.
"""
import zlib
import os

VECTORS = []  # (name, raw_deflate_bytes, expected_bytes)


def add(name: str, data: bytes):
    co = zlib.compressobj(level=9, method=zlib.DEFLATED,
                          wbits=-15)          # raw deflate, no header/trailer
    raw = co.compress(data) + co.flush()
    # sanity: round-trip through python itself
    dec = zlib.decompress(raw, -15)
    assert dec == data, name
    VECTORS.append((name, raw, data))


# 1. empty / tiny
add("empty", b"")
add("one_literal", b"A")
add("few_literals", b"Hello, World!")

# 2. short repeats (distance 1), small lengths
add("rep_len3", b"AAA")
add("rep_len10", b"A" * 10)
add("rep_len100", b"A" * 100)

# 3. lengths that land exactly on / around the length-symbol boundaries
#    codes 257..285 map to lengths 3..258.  Build runs whose optimal match
#    lengths hit 67, 83, 99, 115, 131, 163, 195, 227, 258 etc.
for L in (3, 10, 66, 67, 68, 82, 83, 84, 98, 99, 100, 114, 115, 116,
          130, 131, 132, 162, 163, 164, 194, 195, 196, 226, 227, 228,
          257, 258, 259, 300):
    add("run_%d" % L, bytes([0xAA]) * L)

# 4. long pure repeat (the reported bug: tail bytes)
add("rep_65536_AA", bytes([0xAA]) * 65536)
add("rep_10000_A", b"A" * 10000)
add("rep_50000_A_plus_tail", b"A" * 50000 + b"Hello World")

# 5. repeat + varied tail
add("rep_tail_mixed", b"Z" * 4000 + bytes(range(256)) * 8)

# 6. random data (deterministic LCG) of several sizes
def lcg(n, seed=12345):
    out = bytearray()
    s = seed
    for _ in range(n):
        s = (s * 1103515245 + 12345) & 0x7FFFFFFF
        out.append(s & 0xFF)
    return bytes(out)

for n in (64, 256, 1000, 5000, 20000, 65000):
    add("rand_%d" % n, lcg(n))

# 7. random data with an embedded long repeat (forces distance>1 matches too)
def mixed(n=30000):
    base = bytearray(lcg(n))
    # stamp a long identical run in the middle
    base[5000:5000+2000] = b"\x55" * 2000
    # stamp a repeated-but-offset pattern
    pat = bytes(range(0, 64))
    base[10000:10000+64*30] = pat * 30
    return bytes(base)
add("mixed_long_repeat", mixed())

# 8. high-distance matches: two copies of a 4096-byte block far apart
block = lcg(4096, seed=999)
add("far_distance", block + b"\x00" * 20000 + block)

# ---- emit C header ----
out = []
out.append("/* AUTO-GENERATED by gen_test.py; do not edit. */")
out.append("#ifndef TEST_VECTORS_H")
out.append("#define TEST_VECTORS_H")
out.append("")
out.append('#include "stdint.h"')
out.append("")


def emit_bytes(cname, data: bytes):
    out.append("static const uint8_t %s[%d] = {" % (cname, len(data)))
    line = "    "
    for i, b in enumerate(data):
        line += ("%d," % b)
        if len(line) >= 80:
            out.append(line)
            line = "    "
    if line.strip():
        out.append(line)
    out.append("};")
    out.append("")


for i, (name, raw, data) in enumerate(VECTORS):
    emit_bytes("comp_%d" % i, raw)
    emit_bytes("exp_%d" % i, data)

out.append("typedef struct {")
out.append("    const char *name;")
out.append("    const uint8_t *comp; uint32_t comp_len;")
out.append("    const uint8_t *exp;  uint32_t exp_len;")
out.append("} test_vec_t;")
out.append("")
out.append("static const test_vec_t VECTORS[] = {")
for i, (name, raw, data) in enumerate(VECTORS):
    out.append('    {"%s", comp_%d, %d, exp_%d, %d},'
               % (name, i, len(raw), i, len(data)))
out.append("};")
out.append("")
out.append("#define NVECTORS (sizeof(VECTORS)/sizeof(VECTORS[0]))")
out.append("")
out.append("#endif")
out.append("")

here = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(here, "test_vectors.h"), "w", newline="\n") as f:
    f.write("\n".join(out))

print("wrote %d vectors" % len(VECTORS))
