from pathlib import Path
from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "kernel" / "font_data.inc"
FONT_CANDIDATES = [
    Path(r"C:\Windows\\Fonts\\msyh.ttc"),
    Path(r"C:\Windows\\Fonts\\msyhbd.ttc"),
    Path(r"C:\Windows\\Fonts\\msyhl.ttc"),
    Path(r"C:\Windows\\Fonts\\segoeui.ttf"),
]
SIZE = 14
FIRST = 32
LAST = 126
WIDTH = 14
HEIGHT = 18
CJK_GLYPHS = (
    "中文系统网络声卡微软雅黑域名登录密码文件终端运行关机重启"
    "关于选择播放暂停停止刷新剪切复制粘贴打开"
    "保存新建桌面图标任务管理器电源选项休眠注销"
    "版本号启动菜单帮助设置时间日期用户名无效"
    "准备就绪没有音轨音频不可用驱动程序"
    "正在关机请稍候可以安全关闭计算机"
    "未连接已连接离线在线"
    "浏览记事本命令运行资源管理器"
    "文件夹上一步错误代码文本收集数据"
    "将重新启动调试信息写入串口"
    "未找到设备空闲等待中"
    "三维立方体渲染黑背景旋转"
    "事件处理完成跳过输入输出"
    "微软雅黑字体渲染测试"
)


def render_glyph(font: ImageFont.FreeTypeFont, ch: str):
    image = Image.new("L", (WIDTH, HEIGHT), 0)
    draw = ImageDraw.Draw(image)
    bbox = draw.textbbox((0, 0), ch, font=font)
    glyph_w = bbox[2] - bbox[0]
    glyph_h = bbox[3] - bbox[1]
    x = max(0, (WIDTH - glyph_w) // 2 - bbox[0])
    y = max(0, (HEIGHT - glyph_h) // 2 - bbox[1] - 1)
    draw.text((x, y), ch, fill=255, font=font)
    rows = []
    for yy in range(HEIGHT):
        row = []
        for xx in range(WIDTH):
            row.append(1 if image.getpixel((xx, yy)) >= 96 else 0)
        rows.append(row)
    return rows


def main():
    font_path = next((path for path in FONT_CANDIDATES if path.exists()), FONT_CANDIDATES[-1])
    font = ImageFont.truetype(str(font_path), SIZE)
    cjk_codes = sorted({ord(ch) for ch in CJK_GLYPHS})
    lines = []
    lines.append(f"/* generated by tools/gen_font.py; source font: {font_path.name} */")
    lines.append(f"#define UI_FONT_FIRST {FIRST}")
    lines.append(f"#define UI_FONT_LAST {LAST}")
    lines.append(f"#define UI_FONT_WIDTH {WIDTH}")
    lines.append(f"#define UI_FONT_HEIGHT {HEIGHT}")
    lines.append(f"#define UI_FONT_CJK_COUNT {len(cjk_codes)}")
    lines.append("")
    lines.append("static const uint8_t g_ui_font[][UI_FONT_HEIGHT][UI_FONT_WIDTH] = {")

    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        rows = render_glyph(font, ch)
        lines.append("    {")
        for row in rows:
            lines.append("        {" + ", ".join(str(v) for v in row) + "},")
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append("static const uint32_t g_ui_font_cjk_codepoints[UI_FONT_CJK_COUNT] = {")
    for code in cjk_codes:
        lines.append(f"    0x{code:04X},")
    lines.append("};")
    lines.append("")
    lines.append("static const uint8_t g_ui_font_cjk[][UI_FONT_HEIGHT][UI_FONT_WIDTH] = {")
    for code in cjk_codes:
        rows = render_glyph(font, chr(code))
        lines.append("    {")
        for row in rows:
            lines.append("        {" + ", ".join(str(v) for v in row) + "},")
        lines.append("    },")
    lines.append("};")
    OUT.write_text("\n".join(lines) + "\n", encoding="ascii")


if __name__ == "__main__":
    main()
