"""
Convert all PNG icons in individual/ into a C header file with RGBA8888 data.
Output: include/icons_data.h with g_icon_data[] array and ICON_* enum.
"""
import os
from PIL import Image

INDIVIDUAL_DIR = r"D:\11\monios\monios_x64\assets\icons\individual"
OUTPUT_HEADER = r"D:\11\monios\monios_x64\include\icons_data.h"
ICON_SIZE = 64

def icon_name_to_enum(filename):
    """Convert 'net_wifi.png' -> 'ICON_NET_WIFI'"""
    name = os.path.splitext(filename)[0].upper()
    return "ICON_" + name

def main():
    files = sorted([f for f in os.listdir(INDIVIDUAL_DIR) if f.endswith(".png")])
    print(f"Processing {len(files)} icons...")

    lines = []
    lines.append("/* Auto-generated by tools/gen_icons_data.py - DO NOT EDIT */")
    lines.append("#ifndef _ICONS_DATA_H_")
    lines.append("#define _ICONS_DATA_H_")
    lines.append("")
    lines.append('#include "stdint.h"')
    lines.append("")
    lines.append(f"#define MONIOS_ICON_SIZE {ICON_SIZE}U")
    lines.append(f"#define MONIOS_ICON_COUNT {len(files)}U")
    lines.append(f"#define MONIOS_ICON_BYTES ({ICON_SIZE}U * {ICON_SIZE}U * 4U)")
    lines.append("")

    # Enum
    lines.append("typedef enum {")
    for i, f in enumerate(files):
        enum_name = icon_name_to_enum(f)
        if i < len(files) - 1:
            lines.append(f"    {enum_name} = {i},")
        else:
            lines.append(f"    {enum_name} = {i}")
    lines.append("} monios_icon_id_t;")
    lines.append("")

    # Pixel data
    lines.append("static const uint8_t g_icon_data[MONIOS_ICON_COUNT][MONIOS_ICON_BYTES] = {")
    for idx, f in enumerate(files):
        path = os.path.join(INDIVIDUAL_DIR, f)
        img = Image.open(path).convert("RGBA")
        if img.size != (ICON_SIZE, ICON_SIZE):
            img = img.resize((ICON_SIZE, ICON_SIZE), Image.LANCZOS)
        pixels = list(img.getdata())
        lines.append(f"    /* {f} */")
        lines.append("    {")
        # Output in rows of 16 pixels (64 bytes)
        for row in range(ICON_SIZE):
            row_data = []
            for col in range(ICON_SIZE):
                r, g, b, a = pixels[row * ICON_SIZE + col]
                # Framebuffer is 0x00RRGGBB little-endian => memory order B,G,R,A
                row_data.append(f"0x{b:02X},0x{g:02X},0x{r:02X},0x{a:02X}")
            lines.append("        " + ",".join(row_data) + ",")
        if idx < len(files) - 1:
            lines.append("    },")
        else:
            lines.append("    }")
    lines.append("};")
    lines.append("")
    lines.append("#endif /* _ICONS_DATA_H_ */")
    lines.append("")

    with open(OUTPUT_HEADER, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Written {OUTPUT_HEADER}")
    print(f"Total icons: {len(files)}")
    # Estimate size
    total_bytes = len(files) * ICON_SIZE * ICON_SIZE * 4
    print(f"Approximate data size: {total_bytes / 1024:.1f} KB")

if __name__ == "__main__":
    main()
